/* Selector candidates + stability ranking — docs/02 "Selector candidates".
   Classic script: exposes window.__MCADC.selectors. */
(() => {
  window.__MCADC = window.__MCADC || {};

  /** Framework-minted id prefixes. These change between page loads. */
  const AUTOGEN_PREFIX_RE = /^(mat-|cdk-|ng-|ember|react-|:r)/i;
  /** `input-12`, `field_3`, `ctl:7` — a separator then a bare counter. */
  const TRAILING_COUNTER_RE = /[-_:.]\d+$/;
  /** UUID, or a long hex / base36 blob with no readable word in it. */
  const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const HASH_RE = /^(?:[0-9a-f]{16,}|[a-z0-9]{24,})$/i;

  /**
   * Why an id should not anchor a selector, or null if it looks authored.
   * @param {string} id
   * @returns {string|null}
   */
  const looksAutoGenerated = (id) => {
    if (!id) return 'empty id';
    if (AUTOGEN_PREFIX_RE.test(id)) return 'id has a framework prefix';
    if (UUID_RE.test(id)) return 'id is a UUID';
    if (HASH_RE.test(id)) return 'id looks like a hash';
    if (TRAILING_COUNTER_RE.test(id)) return 'id ends in a bare counter';
    return null;
  };

  /**
   * Escape a value for use inside a double-quoted CSS attribute selector.
   * @param {string} v
   * @returns {string}
   */
  const q = (v) => `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

  /**
   * @param {string} selector
   * @param {ParentNode} root
   * @returns {number} how many elements match, or -1 if the selector is invalid
   */
  const cssCount = (selector, root = document) => {
    try {
      return root.querySelectorAll(selector).length;
    } catch {
      return -1;
    }
  };

  /**
   * @param {string} xpath
   * @param {Node} root   when not the document, the absolute `//` is made relative
   * @returns {number}
   */
  const xpathCount = (xpath, root = document) => {
    try {
      const expr = root === document ? xpath : xpath.replace(/^\/\//, './/');
      const r = document.evaluate(expr, root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      return r.snapshotLength;
    } catch {
      return -1;
    }
  };

  /**
   * XPath string literal — XPath 1.0 has no escapes, so a label containing both
   * quote kinds needs concat().
   * @param {string} s
   * @returns {string}
   */
  const xpathLiteral = (s) => {
    if (!s.includes('"')) return `"${s}"`;
    if (!s.includes("'")) return `'${s}'`;
    return 'concat(' + s.split('"').map((part) => `"${part}"`).join(", '\"', ") + ')';
  };

  /**
   * `form > div:nth-of-type(3) > input:nth-of-type(2)` — walks up to the nearest
   * <form> (or body) so the path is short enough to read.
   * @param {Element} el
   * @returns {string}
   */
  const structuralPath = (el) => {
    /** @type {string[]} */
    const parts = [];
    /** @type {Element|null} */
    let cur = el;
    while (cur && cur !== document.body && cur !== document.documentElement) {
      const tag = cur.tagName.toLowerCase();
      if (tag === 'form') {
        parts.unshift('form');
        break;
      }
      /** @type {Element|null} */
      const parent = cur.parentElement;
      let nth = 1;
      if (parent) {
        let sib = cur.previousElementSibling;
        while (sib) {
          if (sib.tagName === cur.tagName) nth++;
          sib = sib.previousElementSibling;
        }
      }
      parts.unshift(`${tag}:nth-of-type(${nth})`);
      cur = parent;
    }
    if (parts[0] !== 'form') parts.unshift('body');
    return parts.join(' > ');
  };

  /**
   * @param {ControlElement} el
   * @param {string} label
   * @returns {SelectorSet}
   */
  const buildSelectors = (el, label) => {
    const tag = el.tagName.toLowerCase();
    const fcn = el.getAttribute('formcontrolname') || '';
    const name = el.getAttribute('name') || '';
    /** @type {string[]} */
    const notes = [];

    /** @type {Array<{ sel: string, rank: 1|2|3|4|5, css: boolean }>} */
    const candidates = [];

    if (el.id) {
      const why = looksAutoGenerated(el.id);
      if (why) notes.push(`${why} (${el.id})`);
      else candidates.push({ sel: `#${CSS.escape(el.id)}`, rank: 1, css: true });
    }
    if (fcn) candidates.push({ sel: `[formcontrolname=${q(fcn)}]`, rank: 2, css: true });
    if (name) candidates.push({ sel: `[name=${q(name)}]`, rank: 3, css: true });
    if (label) {
      candidates.push({
        sel: `//label[normalize-space()=${xpathLiteral(label)}]/following::${tag}[1]`,
        rank: 4,
        css: false,
      });
    }
    candidates.push({ sel: structuralPath(el), rank: 5, css: true });

    // Pick the first candidate that is unique. A non-unique high-rank candidate
    // is still kept as a fallback because it is often unique in a sub-tree.
    let primaryIdx = -1;
    /** @type {number[]} */
    const counts = candidates.map((c) => (c.css ? cssCount(c.sel) : xpathCount(c.sel)));
    for (let i = 0; i < candidates.length; i++) {
      if (counts[i] === 1) {
        primaryIdx = i;
        break;
      }
      if (counts[i] > 1) notes.push(`${candidates[i].sel} matches ${counts[i]} elements`);
    }
    if (primaryIdx === -1) primaryIdx = 0;

    const primary = candidates[primaryIdx];
    const unique = counts[primaryIdx] === 1;
    /** @type {SelectorStability} */
    let stability = primary.rank <= 2 ? 'stable' : primary.rank === 3 ? 'likely' : 'fragile';
    if (!unique) {
      stability = 'fragile';
      notes.push('primary selector is not unique on the page');
    }

    // Q5: document-wide uniqueness decides stability; form-scoped uniqueness is
    // recorded alongside so a downstream tool can scope its query instead.
    const form = el.closest('form');
    /** @type {boolean|null} */
    let uniqueInForm = null;
    if (form) {
      const n = primary.css ? cssCount(primary.sel, form) : xpathCount(primary.sel, form);
      uniqueInForm = n === 1;
      if (!unique && uniqueInForm) notes.push('unique within its enclosing form');
    }

    return {
      primary: primary.sel,
      fallbacks: candidates.filter((_, i) => i !== primaryIdx).map((c) => c.sel),
      stability,
      unique,
      uniqueInForm,
      notes: notes.join('; '),
    };
  };

  window.__MCADC.selectors = { buildSelectors, looksAutoGenerated };
})();
