/**
 * field-map-draft.json — docs/03. One entry per unique field across all
 * states, keyed by the most stable identifier available, with dependency and
 * transition context. `vcfoField` is always null: a human fills it in.
 */
import { looksAutoGeneratedId } from './selector-hints.js';

/** @typedef {import('../../shared/schema.js').StateRecord} StateRecord */
/** @typedef {import('../../shared/schema.js').FieldRecord} FieldRecord */
/** @typedef {import('../../shared/schema.js').AnyFieldRecord} AnyFieldRecord */
/** @typedef {import('../../shared/schema.js').Dependency} Dependency */
/** @typedef {import('../../shared/schema.js').Transition} Transition */
/** @typedef {import('../../shared/schema.js').FieldMapEntry} FieldMapEntry */
/** @typedef {import('../../shared/schema.js').FieldMapDraft} FieldMapDraft */
/** @typedef {import('../../shared/schema.js').SelectorStability} SelectorStability */

/**
 * Stability order: formControlName, authored id, name, label. Matches the
 * selector ranking so the key usually equals what the primary selector targets.
 * @param {FieldRecord} f
 * @param {Set<string>} [varyingIds]   ids observed to change between captures (Q2)
 * @returns {string}
 */
export function mapKey(f, varyingIds) {
  if (f.formControlName) return f.formControlName;
  if (f.id && !looksAutoGeneratedId(f.id) && !(varyingIds && varyingIds.has(f.id))) return f.id;
  if (f.name) return f.name;
  if (f.label) return f.label;
  return f.id || `${f.type}@${f.index}`;
}

/**
 * The identity used in transitions and dependencies (docs/02 signature rule),
 * so dependency source/target names can be joined to map keys.
 * @param {AnyFieldRecord} f
 * @returns {string}
 */
function signatureKey(f) {
  if ('redactedEntirely' in f) return f.label || `${f.type}@${f.index}`;
  return f.id || f.name || f.formControlName || f.label || `${f.type}@${f.index}`;
}

/**
 * Q2: the same logical field (same path, same formControlName/name/label) seen
 * with different ids across captures means the id is minted per render and
 * must not anchor a selector, whatever it looks like.
 * @param {StateRecord[]} states
 * @returns {Map<string, Set<string>>}   id → every id it was seen alternating with
 */
export function findVaryingIds(states) {
  /** @type {Map<string, Set<string>>} */
  const groups = new Map();
  for (const s of states) {
    for (const f of s.fields) {
      if ('redactedEntirely' in f || !f.id) continue;
      if (!f.formControlName && !f.name && !f.label) continue;
      const g = `${s.pathname}|${f.formControlName}|${f.name}|${f.label}`;
      let ids = groups.get(g);
      if (!ids) groups.set(g, (ids = new Set()));
      ids.add(f.id);
    }
  }
  /** @type {Map<string, Set<string>>} */
  const varying = new Map();
  for (const ids of groups.values()) {
    if (ids.size < 2) continue;
    for (const id of ids) varying.set(id, ids);
  }
  return varying;
}

/**
 * @param {FieldRecord} f
 * @param {Map<string, Set<string>>} varying
 * @returns {{ selectors: FieldMapEntry['selectors'], note: string }}
 */
function selectorsFor(f, varying) {
  const sel = f.selectors;
  const alternates = f.id ? varying.get(f.id) : undefined;
  if (!alternates || !sel.primary.startsWith('#')) {
    return { selectors: { primary: sel.primary, fallbacks: sel.fallbacks, stability: sel.stability }, note: '' };
  }
  // Demote to the best non-id fallback and re-derive stability from its shape.
  const fallbacks = sel.fallbacks.filter((x) => !x.startsWith('#'));
  const primary = fallbacks[0] || sel.primary;
  /** @type {SelectorStability} */
  const stability = primary.startsWith('[formcontrolname=') ? 'stable' : primary.startsWith('[name=') ? 'likely' : 'fragile';
  return {
    selectors: { primary, fallbacks: fallbacks.slice(1), stability },
    note: `id varies across captures (${Array.from(alternates).join(', ')}); id selector demoted`,
  };
}

/**
 * @param {StateRecord[]} states
 * @param {Dependency[]} deps
 * @param {Transition[]} transitions
 * @returns {FieldMapDraft}
 */
export function buildFieldMap(states, deps, transitions) {
  const varying = findVaryingIds(states);
  const varyingIds = new Set(varying.keys());
  /** @type {Map<string, FieldMapEntry>} */
  const byKey = new Map();
  /** @type {Map<string, string>} signature key → map key */
  const sigToMap = new Map();

  /**
   * @param {FieldMapEntry} e
   * @param {string} k
   */
  const addAlt = (e, k) => {
    if (k && k !== e.key && !e.altKeys.includes(k)) e.altKeys.push(k);
  };

  for (const s of states) {
    for (const f of s.fields) {
      if ('redactedEntirely' in f) continue;
      const key = mapKey(f, varyingIds);
      sigToMap.set(signatureKey(f), key);
      const { selectors, note } = selectorsFor(f, varying);
      const existing = byKey.get(key);
      if (existing) {
        if (!existing.seenOnStates.includes(s.id)) existing.seenOnStates.push(s.id);
        for (const k of [f.id, f.name, f.formControlName, f.label]) addAlt(existing, k);
        // Prefer the strongest label and the longest option list seen anywhere.
        if (labelRank(f.labelSource) < labelRank(existing.labelSource)) {
          existing.label = f.label;
          existing.labelSource = f.labelSource;
        }
        if (f.options && (!existing.options || f.options.length > existing.options.length)) existing.options = f.options;
        if (f.required) existing.required = true;
        if (f.maxLength != null && existing.maxLength == null) existing.maxLength = f.maxLength;
        if (f.pattern && !existing.pattern) existing.pattern = f.pattern;
        if (stabilityRank(selectors.stability) < stabilityRank(existing.selectors.stability)) existing.selectors = selectors;
        if (note && !existing.notes.includes('id varies')) existing.notes = [existing.notes, note].filter(Boolean).join('; ');
        continue;
      }
      /** @type {FieldMapEntry} */
      const entry = {
        key,
        altKeys: [],
        seenOnStates: [s.id],
        label: f.label,
        labelSource: f.labelSource,
        type: f.type,
        required: f.required,
        maxLength: f.maxLength,
        pattern: f.pattern,
        selectors,
        options: f.options,
        dependsOn: [],
        affects: [],
        vcfoField: null,
        notes: [f.selectors.notes, note].filter(Boolean).join('; '),
      };
      for (const k of [f.id, f.name, f.formControlName, f.label]) addAlt(entry, k);
      byKey.set(key, entry);
    }
  }

  for (const d of deps) {
    const src = sigToMap.get(d.sourceField) || d.sourceField;
    const srcEntry = byKey.get(src);
    for (const t of d.targetFields) {
      const tgt = sigToMap.get(t) || t;
      const tgtEntry = byKey.get(tgt);
      if (srcEntry && !srcEntry.affects.includes(tgt)) srcEntry.affects.push(tgt);
      if (tgtEntry && !tgtEntry.dependsOn.includes(src)) tgtEntry.dependsOn.push(src);
    }
    if (srcEntry && d.viaNetwork && d.endpoint && !srcEntry.notes.includes(d.endpoint)) {
      srcEntry.notes = [srcEntry.notes, `change triggers ${d.endpoint}`].filter(Boolean).join('; ');
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    fields: Array.from(byKey.values()),
    dependencies: deps,
    transitions,
  };
}

/** @param {string} src */
function labelRank(src) {
  return ['for', 'wrap', 'aria-labelledby', 'aria-label', 'container', 'sibling', 'placeholder', 'none'].indexOf(src);
}

/** @param {string} st */
function stabilityRank(st) {
  return ['stable', 'likely', 'fragile'].indexOf(st);
}
