/**
 * Auto-generated id heuristic, background copy. The content-world original is
 * in content/lib/selectors.js and cannot be imported from a module. Keep the
 * two regex sets identical.
 */

const AUTOGEN_PREFIX_RE = /^(mat-|cdk-|ng-|ember|react-|:r)/i;
const TRAILING_COUNTER_RE = /[-_:.]\d+$/;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const HASH_RE = /^(?:[0-9a-f]{16,}|[a-z0-9]{24,})$/i;

/**
 * @param {string} id
 * @returns {boolean}
 */
export function looksAutoGeneratedId(id) {
  return !id || AUTOGEN_PREFIX_RE.test(id) || UUID_RE.test(id) || HASH_RE.test(id) || TRAILING_COUNTER_RE.test(id);
}
