/**
 * playwright-skeleton.ts — docs/03, docs/08 "Why the skeleton is commented
 * out". A correct shape for a coding agent to start from: selectors, one
 * function per page state, every fill/click line commented. Never runnable
 * as generated; nothing in it has been executed.
 */
import { TOOL_NAME, TOOL_VERSION } from '../../shared/constants.js';
import { stemFor, identifier } from './naming.js';

/** @typedef {import('../../shared/schema.js').StateRecord} StateRecord */
/** @typedef {import('../../shared/schema.js').FlowMap} FlowMap */
/** @typedef {import('../../shared/schema.js').FlowMapControl} FlowMapControl */
/** @typedef {import('../../shared/schema.js').SelectorsFile} SelectorsFile */
/** @typedef {import('../../shared/schema.js').Transition} Transition */

/**
 * @param {string} s
 * @returns {string}
 */
const tsString = (s) => JSON.stringify(s);

/**
 * @param {string} s
 * @returns {string}   safe inside a // comment
 */
const oneLine = (s) => s.replace(/[\r\n]+/g, ' ').replace(/\*\//g, '* /');

/**
 * The Playwright call that fits a control, as a commented line.
 * @param {FlowMapControl} c
 * @param {string} keyExpr
 * @returns {string}
 */
function callFor(c, keyExpr) {
  const data = `data[${tsString(c.key)}]`;
  const meta = [c.type, c.required ? 'required' : '', c.maxLength != null ? `maxLength ${c.maxLength}` : '', c.options ? `${c.options.length} options` : '', c.entry && c.entry.mode === 'widget' ? `WIDGET: ${c.entry.widgetKind || c.entry.evidence}` : '']
    .filter(Boolean)
    .join(', ');
  let call;
  if (c.type === 'select') call = `await page.selectOption(${keyExpr}, ${data});`;
  else if (c.type === 'checkbox' || c.type === 'radio' || c.type === 'switch') call = `await page.check(${keyExpr});`;
  else if (c.type === 'file') call = `await page.setInputFiles(${keyExpr}, ${data});`;
  else if (c.entry && c.entry.mode === 'widget') call = `await page.click(${keyExpr}); // then drive the ${c.entry.widgetKind || 'widget'}`;
  else call = `await page.fill(${keyExpr}, ${data});`;
  return `  // ${call} // ${oneLine(meta)}${c.label ? ` — "${oneLine(c.label)}"` : ''}`;
}

/**
 * @param {StateRecord[]} states
 * @param {FlowMap} map
 * @param {SelectorsFile} selectors
 * @returns {string}
 */
export function buildSkeleton(states, map, selectors) {
  /** @type {string[]} */
  const out = [];
  out.push('/**');
  out.push(` * playwright-skeleton.ts — generated by ${TOOL_NAME} ${TOOL_VERSION} on ${new Date().toISOString()}`);
  out.push(` * for ${map.origin} (${map.framework}).`);
  out.push(' *');
  out.push(' * NOT RUNNABLE BY DESIGN. Every fill and click line is commented out. Credentials,');
  out.push(' * waits, navigation and error handling are absent on purpose, and nothing in this');
  out.push(' * file has been executed. A capture describes what a site looked like once; it is');
  out.push(' * not validated automation. Uncomment deliberately, verify each selector at');
  out.push(' * runtime, and leave login, OTP, captcha, payment and final submission to a human.');
  out.push(' *');
  out.push(' * Controls inside shadow roots need SHADOW_PATHS: query each host in order, then');
  out.push(' * the selector inside the last root. Playwright pierces open shadow roots for CSS');
  out.push(' * selectors automatically; other tools may not.');
  out.push(' */');
  out.push('');
  out.push('// Minimal structural type so this file type-checks without Playwright installed.');
  out.push("// Replace with: import type { Page } from '@playwright/test';");
  out.push('type Page = {');
  out.push('  goto(url: string): Promise<unknown>;');
  out.push('  fill(selector: string, value: string): Promise<void>;');
  out.push('  click(selector: string): Promise<void>;');
  out.push('  check(selector: string): Promise<void>;');
  out.push('  selectOption(selector: string, value: string): Promise<unknown>;');
  out.push('  setInputFiles(selector: string, files: string): Promise<void>;');
  out.push('};');
  out.push('');
  out.push('export type Data = Record<string, string>;');
  out.push('');
  out.push('export const SELECTORS = {');
  for (const [k, v] of Object.entries(selectors.selectors)) out.push(`  ${tsString(k)}: ${tsString(v)},`);
  out.push('} as const;');
  out.push('');
  out.push('export const FALLBACKS: Record<string, readonly string[]> = {');
  for (const [k, v] of Object.entries(selectors.fallbacks)) out.push(`  ${tsString(k)}: ${JSON.stringify(v)},`);
  out.push('};');
  out.push('');
  out.push('export const SHADOW_PATHS: Record<string, readonly string[]> = {');
  for (const [k, v] of Object.entries(selectors.shadowPaths)) out.push(`  ${tsString(k)}: ${JSON.stringify(v)},`);
  out.push('};');
  out.push('');

  const edgesFrom = new Map();
  for (const t of map.transitions) {
    const arr = edgesFrom.get(t.from) || [];
    arr.push(t);
    edgesFrom.set(t.from, arr);
  }
  const byId = new Map(states.map((s) => [s.id, s]));
  const controlsOnState = new Map();
  for (const c of map.controls) for (const sid of c.seenOnStates) {
    const arr = controlsOnState.get(sid) || [];
    arr.push(c);
    controlsOnState.set(sid, arr);
  }

  /** @type {string[]} */
  const fnNames = [];
  for (const s of states) {
    const fn = `${identifier(stemFor(s).replace(/^\d+-/, ''))}_${s.seq}`;
    fnNames.push(fn);
    const page = map.pages.find((p) => p.stateId === s.id);
    out.push(`// ${s.id} — ${tsString(s.title || s.pathname)} (${s.pathname})${page ? `, reached by ${oneLine(page.reachedBy)}` : ''}`);
    if (s.errors.length) out.push(`// errors visible at capture: ${oneLine(s.errors.slice(0, 3).join(' | '))}`);
    out.push(`export async function ${fn}(page: Page, data: Data): Promise<void> {`);
    const controls = /** @type {FlowMapControl[]} */ (controlsOnState.get(s.id) || []);
    if (!controls.length) out.push('  // no controls on this state');
    for (const c of controls) out.push(callFor(c, `SELECTORS[${tsString(c.key)}]`));
    const dangerous = s.buttons.filter((b) => b.danger && b.visible);
    for (const b of dangerous) out.push(`  // DANGER: "${oneLine(b.text)}" (${oneLine(b.selector)}) — leave to the human`);
    for (const t of /** @type {Transition[]} */ (edgesFrom.get(s.id) || [])) {
      const to = byId.get(t.to);
      const what = [
        t.urlChanged && to ? `navigated to ${to.pathname}` : '',
        t.fieldsAdded.length ? `added ${t.fieldsAdded.length} control(s): ${t.fieldsAdded.slice(0, 5).join(', ')}${t.fieldsAdded.length > 5 ? '…' : ''}` : '',
        t.fieldsRemoved.length ? `removed ${t.fieldsRemoved.length}` : '',
        t.optionsChanged.length ? `options changed on ${t.optionsChanged.map((o) => o.key).join(', ')}` : '',
        t.listCountsChanged.length ? `list counts changed` : '',
        t.errorsAppeared.length ? `${t.errorsAppeared.length} error(s) appeared` : '',
        t.netCallsBetween.length ? `${t.netCallsBetween.length} network call(s)` : '',
      ]
        .filter(Boolean)
        .join('; ');
      out.push(`  // TODO transition: ${oneLine(t.trigger)} → ${t.to}${what ? ` — ${oneLine(what)}` : ''}`);
    }
    out.push('}');
    out.push('');
  }

  out.push('// The captured order. Uncomment and add waits between steps once verified.');
  out.push('export async function flow(page: Page, data: Data): Promise<void> {');
  out.push(`  // await page.goto(${tsString(map.origin)});`);
  for (const fn of fnNames) out.push(`  // await ${fn}(page, data);`);
  out.push('  void page;');
  out.push('  void data;');
  out.push('}');
  out.push('');
  return out.join('\n');
}
