/**
 * Type-only declarations for the classic-script content world. Never loaded by
 * the extension; exists so `tsc --noEmit` can check the content scripts, which
 * share code through `window.__FP` instead of imports.
 */

type ControlRecord = import('../shared/schema.js').ControlRecord;
type AnyControlRecord = import('../shared/schema.js').AnyControlRecord;
type LabelSource = import('../shared/schema.js').LabelSource;
type SelectorSet = import('../shared/schema.js').SelectorSet;
type SelectorStability = import('../shared/schema.js').SelectorStability;
type SelectOption = import('../shared/schema.js').SelectOption;
type ButtonRecord = import('../shared/schema.js').ButtonRecord;
type StepRecord = import('../shared/schema.js').StepRecord;
type StateDraft = import('../shared/schema.js').StateDraft;
type NetDraft = import('../shared/schema.js').NetDraft;
type FrameworkInfo = import('../shared/schema.js').FrameworkInfo;
type AuthHints = import('../shared/schema.js').AuthHints;
type ListPatterns = import('../shared/schema.js').ListPatterns;
type TablePattern = import('../shared/schema.js').TablePattern;
type RepeatPattern = import('../shared/schema.js').RepeatPattern;
type PaginationPattern = import('../shared/schema.js').PaginationPattern;
type DownloadPattern = import('../shared/schema.js').DownloadPattern;
type RepeatSlot = import('../shared/schema.js').RepeatSlot;
type OpaqueRegion = import('../shared/schema.js').OpaqueRegion;
type EntryHint = import('../shared/schema.js').EntryHint;
type NavInventory = import('../shared/schema.js').NavInventory;
type NavItem = import('../shared/schema.js').NavItem;
type ViewGroup = import('../shared/schema.js').ViewGroup;
type ViewOption = import('../shared/schema.js').ViewOption;
type ViewState = import('../shared/schema.js').ViewState;
type ActionDraft = import('../shared/schema.js').ActionDraft;
type ActionSelectors = import('../shared/schema.js').ActionSelectors;
type ActionTargetType = import('../shared/schema.js').ActionTargetType;
type JsonShape = import('../shared/schema.js').JsonShape;

/** Any element we treat as a control (native or ARIA widget). */
type ControlElement = HTMLElement;

interface FPRedactRule {
  name: string;
  pattern: RegExp;
  replacement: string | ((m: string) => string);
}

interface FPPack {
  name: string;
  rules: FPRedactRule[];
}

interface FPRedact {
  redactValue(value: unknown): string;
  isCredentialControl(el: Element, label: string): boolean;
  scrubBody(text: string | null | undefined): string | null;
  scrubText(text: string): string;
  setPacks(names: string[]): void;
  getPacks(): string[];
  CREDENTIAL_RE: RegExp;
}

interface FPFramework {
  /** DOM-only detection, merged with whatever the MAIN world reported. */
  detect(): FrameworkInfo;
  /** Called when the MAIN-world hook answers a detect request. */
  mergeMainWorld(info: Partial<FrameworkInfo>): void;
  current(): FrameworkInfo | null;
}

interface FPLabels {
  resolveLabel(el: Element): { label: string; labelSource: LabelSource };
  cleanText(text: string | null | undefined, max?: number): string;
  textOf(el: Element | null, max?: number): string;
  /** ARIA-order name from textContent; value holders are named by their label only. Not scrubbed. */
  accessibleName(el: Element, max?: number): string;
}

interface FPSelectors {
  buildSelectors(el: Element, label: string, framework: FrameworkInfo): SelectorSet;
  /** Best single selector for an arbitrary element (containers, buttons, items). */
  forElement(el: Element, scope?: ParentNode): string;
  /** Ordered host selectors from the document down to the element's shadow root. */
  hostPath(el: Element): string[];
  /** The Document or ShadowRoot that contains the element. */
  rootOf(el: Element): Document | ShadowRoot;
  looksAutoGenerated(id: string): string | null;
  /** Selector for `el` relative to `ancestor` (tag + stable classes + nth-of-type). */
  relativeSelector(el: Element, ancestor: Element): string;
}

interface FPFields {
  /** Every control in DOM order, descending into open shadow roots. */
  collectControls(root: ParentNode): ControlElement[];
  describeControl(el: ControlElement, index: number, framework: FrameworkInfo): AnyControlRecord;
  isVisible(el: Element): boolean;
  /** querySelectorAll across the root and every open shadow root beneath it. */
  queryDeep(root: ParentNode, selector: string): Element[];
  /** Hosts with a shadow root we cannot see into. */
  findOpaque(root: ParentNode): OpaqueRegion[];
  /** True when any open shadow root exists beneath root. */
  hasShadowRoots(root: ParentNode): boolean;
}

interface FPLists {
  collect(root: ParentNode): ListPatterns;
  /** docs/12 B4: which pagination control `el` is; null when it is none. */
  paginationRoleOf(el: Element): 'next' | 'prev' | 'page' | 'load-more' | null;
  /** docs/12 B4: `containerSelector` of the nearest table or repeat container around `el`. */
  listContainerOf(el: Element): string | null;
}

interface FPDomSnapshot {
  /** Sanitised, redacted, gzipped, base64. Null if anything failed. */
  snapshot(): Promise<string | null>;
}

/** docs/12 B3. */
interface FPNav {
  collect(root: ParentNode): NavInventory;
  /** Labels from the menu root down to `el`, inclusive; empty when `el` is not a menu item. */
  menuPathOf(el: Element): string[];
  /** True when `el` sits inside a navigation or menu region. */
  inNav(el: Element): boolean;
  /** The view group `el` is an option of, by `ViewGroup.name`; null otherwise. */
  viewGroupOf(el: Element, inventory?: NavInventory): string | null;
  /** View state from an inventory plus the current pagination indicators. */
  viewState(inventory: NavInventory, lists: ListPatterns): ViewState;
  /** docs/12 B1: pathname plus the fragment's path part, scrubbed. */
  route(): string;
  /** docs/12 B1: parameter names only. */
  queryKeys(): string[];
  /** Path plus fragment path of an href, scrubbed; null for scripted or empty hrefs. */
  cleanHref(href: string | null): string | null;
  /** Remembers the menu items present now when a mutation batch touched navigation (overlay menus). */
  noteMutations(records: MutationRecord[]): void;
  /** Sorted selectors of the popup menus and nav <details> open right now; '' when none. */
  openKey(): string;
}

interface FPObserveOptions {
  /** `action` is present for user clicks and changes (docs/12 B4). */
  onTrigger(trigger: string, action?: ActionDraft): void;
  /** Called once when the mutation breaker trips, with the cooldown end time. */
  onThrottle(untilEpochMs: number): void;
  /** docs/12 B4: the owner of the danger-word list decides; absent means nothing is flagged. */
  isDanger?(text: string, el: Element): boolean;
  /** docs/12 B4: view key of the last state built, for `ActionDraft.viewKey`. */
  viewKey?(): string;
}

interface FPObserve {
  start(opts: FPObserveOptions): void;
  stop(): void;
  /** True while dom-change triggers are cut by the breaker (A2). */
  degraded(): boolean;
}

interface FPNamespace {
  packs: Record<string, FPPack>;
  redact: FPRedact;
  framework: FPFramework;
  labels: FPLabels;
  selectors: FPSelectors;
  fields: FPFields;
  lists: FPLists;
  domSnapshot: FPDomSnapshot;
  observe: FPObserve;
  nav: FPNav;
}

interface Window {
  __FP: Partial<FPNamespace>;
  /** Set by the MAIN-world hook so a reinjected copy never double-wraps. */
  __fpHooked?: boolean;
}

/** Envelopes the MAIN-world hook posts via window.postMessage. */
type FPNetMessage = { __fp: 'net'; entry: NetDraft };
type FPNavMessage = { __fp: 'nav'; kind: string };
type FPFrameworkMessage = { __fp: 'framework'; info: Partial<FrameworkInfo> };
type FPDetectRequest = { __fp: 'detect' };
/** docs/12 B5: isolated world → MAIN world, sent after the consent gate and on every change. */
type FPConfigMessage = { __fp: 'config'; keepBodies: 'shape' | 'full' };
/** docs/12 B6: MAIN world → isolated world. */
type FPBlobMessage = { __fp: 'blob'; mime: string; size: number; at: string };
type FPOpenMessage = { __fp: 'open'; url: string | null; target: string | null; at: string };
type FPWindowMessage = FPNetMessage | FPNavMessage | FPFrameworkMessage | FPDetectRequest | FPConfigMessage | FPBlobMessage | FPOpenMessage;
