/**
 * Type-only declarations for the classic-script content world. Never loaded by
 * the extension; exists so `tsc --noEmit` can check the content scripts, which
 * share code through `window.__FP` instead of imports.
 */

type ControlRecord = import('../shared/schema.js').ControlRecord;
type AnyControlRecord = import('../shared/schema.js').AnyControlRecord;
type LabelSource = import('../shared/schema.js').LabelSource;
type SelectorSet = import('../shared/schema.js').SelectorSet;
type SelectorStability = import('../shared/schema.js').SelectorStability;
type SelectOption = import('../shared/schema.js').SelectOption;
type ButtonRecord = import('../shared/schema.js').ButtonRecord;
type StepRecord = import('../shared/schema.js').StepRecord;
type StateDraft = import('../shared/schema.js').StateDraft;
type NetDraft = import('../shared/schema.js').NetDraft;
type FrameworkInfo = import('../shared/schema.js').FrameworkInfo;
type AuthHints = import('../shared/schema.js').AuthHints;
type ListPatterns = import('../shared/schema.js').ListPatterns;
type TablePattern = import('../shared/schema.js').TablePattern;
type RepeatPattern = import('../shared/schema.js').RepeatPattern;
type PaginationPattern = import('../shared/schema.js').PaginationPattern;
type DownloadPattern = import('../shared/schema.js').DownloadPattern;
type RepeatSlot = import('../shared/schema.js').RepeatSlot;
type OpaqueRegion = import('../shared/schema.js').OpaqueRegion;
type EntryHint = import('../shared/schema.js').EntryHint;

/** Any element we treat as a control (native or ARIA widget). */
type ControlElement = HTMLElement;

interface FPRedactRule {
  name: string;
  pattern: RegExp;
  replacement: string | ((m: string) => string);
}

interface FPPack {
  name: string;
  rules: FPRedactRule[];
}

interface FPRedact {
  redactValue(value: unknown): string;
  isCredentialControl(el: Element, label: string): boolean;
  scrubBody(text: string | null | undefined): string | null;
  scrubText(text: string): string;
  setPacks(names: string[]): void;
  getPacks(): string[];
  CREDENTIAL_RE: RegExp;
}

interface FPFramework {
  /** DOM-only detection, merged with whatever the MAIN world reported. */
  detect(): FrameworkInfo;
  /** Called when the MAIN-world hook answers a detect request. */
  mergeMainWorld(info: Partial<FrameworkInfo>): void;
  current(): FrameworkInfo | null;
}

interface FPLabels {
  resolveLabel(el: Element): { label: string; labelSource: LabelSource };
  cleanText(text: string | null | undefined, max?: number): string;
  textOf(el: Element | null, max?: number): string;
}

interface FPSelectors {
  buildSelectors(el: Element, label: string, framework: FrameworkInfo): SelectorSet;
  /** Best single selector for an arbitrary element (containers, buttons, items). */
  forElement(el: Element, scope?: ParentNode): string;
  /** Ordered host selectors from the document down to the element's shadow root. */
  hostPath(el: Element): string[];
  /** The Document or ShadowRoot that contains the element. */
  rootOf(el: Element): Document | ShadowRoot;
  looksAutoGenerated(id: string): string | null;
  /** Selector for `el` relative to `ancestor` (tag + stable classes + nth-of-type). */
  relativeSelector(el: Element, ancestor: Element): string;
}

interface FPFields {
  /** Every control in DOM order, descending into open shadow roots. */
  collectControls(root: ParentNode): ControlElement[];
  describeControl(el: ControlElement, index: number, framework: FrameworkInfo): AnyControlRecord;
  isVisible(el: Element): boolean;
  /** querySelectorAll across the root and every open shadow root beneath it. */
  queryDeep(root: ParentNode, selector: string): Element[];
  /** Hosts with a shadow root we cannot see into. */
  findOpaque(root: ParentNode): OpaqueRegion[];
  /** True when any open shadow root exists beneath root. */
  hasShadowRoots(root: ParentNode): boolean;
}

interface FPLists {
  collect(root: ParentNode): ListPatterns;
}

interface FPDomSnapshot {
  /** Sanitised, redacted, gzipped, base64. Null if anything failed. */
  snapshot(): Promise<string | null>;
}

interface FPObserveOptions {
  onTrigger(trigger: string): void;
  /** Called once when the mutation breaker trips, with the cooldown end time. */
  onThrottle(untilEpochMs: number): void;
}

interface FPObserve {
  start(opts: FPObserveOptions): void;
  stop(): void;
  /** True while dom-change triggers are cut by the breaker (A2). */
  degraded(): boolean;
}

interface FPNamespace {
  packs: Record<string, FPPack>;
  redact: FPRedact;
  framework: FPFramework;
  labels: FPLabels;
  selectors: FPSelectors;
  fields: FPFields;
  lists: FPLists;
  domSnapshot: FPDomSnapshot;
  observe: FPObserve;
}

interface Window {
  __FP: Partial<FPNamespace>;
  /** Set by the MAIN-world hook so a reinjected copy never double-wraps. */
  __fpHooked?: boolean;
}

/** Envelopes the MAIN-world hook posts via window.postMessage. */
type FPNetMessage = { __fp: 'net'; entry: NetDraft };
type FPNavMessage = { __fp: 'nav'; kind: string };
type FPFrameworkMessage = { __fp: 'framework'; info: Partial<FrameworkInfo> };
type FPDetectRequest = { __fp: 'detect' };
type FPWindowMessage = FPNetMessage | FPNavMessage | FPFrameworkMessage | FPDetectRequest;
