/**
 * Type-only declarations for the classic-script content world. Never loaded by
 * the extension; exists so `tsc --noEmit` can check the content scripts, which
 * share code through `window.__MCADC` instead of imports.
 */

type FieldRecord = import('../shared/schema.js').FieldRecord;
type AnyFieldRecord = import('../shared/schema.js').AnyFieldRecord;
type LabelSource = import('../shared/schema.js').LabelSource;
type SelectorSet = import('../shared/schema.js').SelectorSet;
type SelectorStability = import('../shared/schema.js').SelectorStability;
type SelectOption = import('../shared/schema.js').SelectOption;
type ButtonRecord = import('../shared/schema.js').ButtonRecord;
type StepRecord = import('../shared/schema.js').StepRecord;
type StateDraft = import('../shared/schema.js').StateDraft;
type NetDraft = import('../shared/schema.js').NetDraft;

/** Any element we treat as a form control. */
type ControlElement = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | HTMLElement;

interface MCADCRedact {
  /** `<n chars>` for non-empty values, '' otherwise. */
  redactValue(value: unknown): string;
  /** Rule 2: true when the control must be recorded only as `redactedEntirely`. */
  isCredentialControl(el: ControlElement, label: string): boolean;
  /** Rule 3: regex pass over request/response bodies. */
  scrubBody(text: string | null | undefined): string | null;
  /** Free text that may contain PII (labels, headings): same regex pass. */
  scrubText(text: string): string;
  CREDENTIAL_RE: RegExp;
}

interface MCADCLabels {
  resolveLabel(el: ControlElement): { label: string; labelSource: LabelSource };
  cleanText(text: string | null | undefined, max?: number): string;
}

interface MCADCSelectors {
  buildSelectors(el: ControlElement, label: string): SelectorSet;
  looksAutoGenerated(id: string): string | null;
}

interface MCADCFields {
  collectControls(root: Document | Element): ControlElement[];
  describeField(el: ControlElement, index: number): AnyFieldRecord;
  fieldKey(f: AnyFieldRecord): string;
  isVisible(el: Element): boolean;
}

interface MCADCDomSnapshot {
  /** Sanitised, redacted, gzipped, base64. Null if anything failed. */
  snapshot(): Promise<string | null>;
}

interface MCADCObserve {
  start(onTrigger: (trigger: string) => void): void;
  stop(): void;
}

interface MCADCNamespace {
  redact: MCADCRedact;
  labels: MCADCLabels;
  selectors: MCADCSelectors;
  fields: MCADCFields;
  domSnapshot: MCADCDomSnapshot;
  observe: MCADCObserve;
}

interface Window {
  __MCADC: Partial<MCADCNamespace>;
  /** Set by the MAIN-world hooks so a reinjected copy never double-wraps. */
  __mcadcHooked?: boolean;
  __mcadcNavHooked?: boolean;
}

/** Shape of what the MAIN-world hook posts via window.postMessage. */
type MCADCNetMessage = { __mcadc: 'net'; entry: NetDraft };
type MCADCNavMessage = { __mcadc: 'nav'; kind: string };
type MCADCWindowMessage = MCADCNetMessage | MCADCNavMessage;
